<?php
namespace App\Scripts\php;

class Data {

    public static function feeds(){
        return  
        [
            //LA LIBRE
        'http://www.lalibre.be/rss/section/actu/politique-belge.xml',
        'http://www.lalibre.be/rss.xml',
        'http://www.lalibre.be/rss/dossier/5b34c7ba55324d3f130abf58.xml',
        'http://www.lalibre.be/rss/section/regions/namur.xml',
        'http://www.lalibre.be/rss/section/network.xml',
        'http://www.lalibre.be/rss/section/actu.xml',
        'http://www.lalibre.be/rss/section/actu/international.xml',
        'http://www.lalibre.be/rss/section/actu/belgique.xml',
        'http://www.lalibre.be/rss/section/actu/politique-belge.xml',
        'http://www.lalibre.be/rss/section/actu/sciences-sante.xml',
        'http://www.lalibre.be/rss/section/actu/planete.xml',
        'http://www.lalibre.be/rss/section/actu/planete/inspire.xml',
        'http://www.lalibre.be/rss/section/actu/personnalite.xml',
        'http://www.lalibre.be/rss/section/economie.xml',
        'http://www.lalibre.be/rss/section/economie/immo.xml',
        'http://www.lalibre.be/rss/section/economie/digital.xml',
        'http://www.lalibre.be/rss/section/economie/libre-entreprise.xml',
        'http://www.lalibre.be/rss/section/economie/emploi.xml',
        'http://www.lalibre.be/rss/section/economie/conjoncture.xml',
        'http://www.lalibre.be/rss/section/economie/eco-debats.xml',
        'http://www.lalibre.be/rss/section/economie/placements.xml',
        'http://www.lalibre.be/rss/section/economie/auto.xml',
        'http://www.lalibre.be/rss/section/culture.xml',
        'http://www.lalibre.be/rss/section/culture/cinema.xml',
        'http://www.lalibre.be/rss/section/culture/musique.xml',
        'http://www.lalibre.be/rss/section/culture/arts.xml',
        'http://www.lalibre.be/rss/section/culture/medias-tele.xml',
        'http://www.lalibre.be/rss/section/culture/livres-bd.xml',
        'http://www.lalibre.be/rss/section/culture/serie-tv.xml',
        'http://www.lalibre.be/rss/section/culture/scenes.xml',
        'http://www.lalibre.be/rss/section/culture/politique.xml',
        'http://www.lalibre.be/rss/section/sports.xml',
        'http://www.lalibre.be/rss/section/debats.xml',
        'http://www.lalibre.be/rss/section/regions.xml',
        'http://www.lalibre.be/rss/section/regions/bruxelles.xml',
        'http://www.lalibre.be/rss/section/regions/brabant.xml',
        'http://www.lalibre.be/rss/section/regions/flandre.xml',
        'http://www.lalibre.be/rss/section/regions/liege.xml',
        'http://www.lalibre.be/rss/section/regions/hainaut.xml',
        'http://www.lalibre.be/rss/section/regions/namur.xml',
        'http://www.lalibre.be/rss/infos/belga.xml',
        'http://www.lalibre.be/rss/infos/afp.xml',
        'http://www.lalibre.be/rss/dossiers.xml',

        // LE SOIR
        'http://www.lesoir.be/rss/81851/cible_principale_gratuit',
        'http://www.lesoir.be/rss/81862/cible_principale_gratuit',
        'http://www.lesoir.be/rss/31868/cible_principale',
        'http://www.lesoir.be/rss/31867/cible_principale',
        'http://www.lesoir.be/rss/81864/cible_principale_gratuit',
        'http://www.lesoir.be/rss/31871/cible_principale',
        'http://www.lesoir.be/rss/31872/cible_principale',
        'http://www.lesoir.be/rss/31873/cible_principale',
        'http://www.lesoir.be/rss/31874/cible_principale',
        'http://www.lesoir.be/rss/81863/cible_principale_gratuit',
        'http://www.lesoir.be/rss/31875/cible_principale',
        'http://www.lesoir.be/rss/31876/cible_principale',
        'http://www.lesoir.be/rss/81866/cible_principale_gratuit',
        'http://www.lesoir.be/rss/81906/cible_principale_gratuit',
        'http://www.lesoir.be/rss/81907/cible_principale_gratuit',
        'http://www.lesoir.be/rss/81867/cible_principale_gratuit',
        'http://www.lesoir.be/rss/12/cible_principale',
        'http://www.lesoir.be/rss/81868/cible_principale_gratuit',
        'http://www.lesoir.be/rss/31895/cible_principale',
        'http://www.lesoir.be/rss/16/cible_principale',
        'http://www.lesoir.be/rss/23/cible_principale',
        'http://www.lesoir.be/rss/31920/maga_cible_principale_gratuit',
        //LA DH
        'http://www.dhnet.be/rss.xml',
        'http://www.dhnet.be/rss/section/actu.xml',
        'http://www.dhnet.be/rss/section/actu/faits.xml',
        'http://www.dhnet.be/rss/section/actu/belgique.xml',
        'http://www.dhnet.be/rss/section/actu/societe.xml',
        'http://www.dhnet.be/rss/section/actu/monde.xml',
        'http://www.dhnet.be/rss/section/actu/economie.xml',
        'http://www.dhnet.be/rss/section/actu/new-tech.xml',
        'http://www.dhnet.be/rss/section/actu/sexualite.xml',
        'http://www.dhnet.be/rss/section/actu/sante.xml',
        'http://www.dhnet.be/rss/section/sports.xml',
        'http://www.dhnet.be/rss/section/regions.xml',
        'http://www.dhnet.be/rss/section/regions/bruxelles.xml',
        'http://www.dhnet.be/rss/section/regions/brabant.xml',
        'http://www.dhnet.be/rss/section/regions/namur.xml',
        'http://www.dhnet.be/rss/section/regions/luxembourg.xml',
        'http://www.dhnet.be/rss/section/regions/liege.xml',
        'http://www.dhnet.be/rss/section/regions/charleroi.xml',
        'http://www.dhnet.be/rss/section/regions/mons.xml',
        'http://www.dhnet.be/rss/section/regions/centre.xml',
        'http://www.dhnet.be/rss/section/regions/tournai-ath-mouscron.xml',
        'http://www.dhnet.be/rss/section/medias.xml',
        'http://www.dhnet.be/rss/section/medias/television.xml',
        'http://www.dhnet.be/rss/section/medias/cinema.xml',
        'http://www.dhnet.be/rss/section/medias/musique.xml',
        'http://www.dhnet.be/rss/section/medias/jeux-video.xml',
        'http://www.dhnet.be/rss/section/medias/livresbd.xml',
        'http://www.dhnet.be/rss/section/medias/dh-radio.xml',
        'http://www.dhnet.be/rss/section/medias/divers.xml',
        'http://www.dhnet.be/rss/section/medias/series.xml',
        'http://www.dhnet.be/rss/section/buzz.xml',
        'http://www.dhnet.be/rss/section/conso.xml',

        //RTL INFO
        'http://feeds.feedburner.com/rtlinfo/belgique?format=xml',
        'http://feeds.feedburner.com/Rtlinfo/VotreRegion?format=xml',
        'https://feeds.feedburner.com/Rtlinfos-ALaUne',
        'https://feeds.feedburner.com/rtlinfo/france',
        'https://feeds.feedburner.com/Rtlinfo/VotreRegion',
        'https://feeds.feedburner.com/RTLInternational',
        'https://feeds.feedburner.com/RTLEconomie',
        'https://feeds.feedburner.com/RTLSports',
        'https://feeds.feedburner.com/rtlsport/football',
        'https://feeds.feedburner.com/rtlinfo/people',
        'https://feeds.feedburner.com/rtlpeople/royaute',
        'https://feeds.feedburner.com/rtlpeople/buzz',
        'https://feeds.feedburner.com/rtlsport/footballetranger',

        //L'ECHO
        'https://www.lecho.be/rss/actualite.xml',
        'https://www.lecho.be/rss/politique_europe.xml',
        'https://www.lecho.be/rss/politique_belgique.xml',
        'https://www.lecho.be/rss/fonds.xml',
        'https://www.lecho.be/rss/mon_argent_energie.xml',
        'https://www.lecho.be/rss/mon_argent_impots.xml',
        'https://www.lecho.be/rss/mon_argent_budget.xml',
        'https://www.lecho.be/rss/mon_argent.xml',
        'https://www.lecho.be/rss/mon_argent_credit.xml',
        'https://www.lecho.be/rss/mon_argent_succession.xml',
        'https://www.lecho.be/rss/mon_argent_voyages.xml',
        'https://www.lecho.be/rss/mon_argent_immobilier.xml',
        'https://www.lecho.be/rss/mon_argent_assurances.xml',
        'https://www.lecho.be/rss/mon_argent_epargner.xml',
        'https://www.lecho.be/rss/sabato_art.xml',
        'https://www.lecho.be/rss/sabato_mode.xml',
        'https://www.lecho.be/rss/sabato_gastronomie.xml',
        'https://www.lecho.be/rss/sabato_filmsettv.xml',
        'https://www.lecho.be/rss/sabato_design.xml',
        'https://www.lecho.be/rss/sabato_general.xml',
        'https://www.lecho.be/rss/entreprises.xml',
        'https://www.lecho.be/rss/entreprises_banques.xml',
        'https://www.lecho.be/rss/top_stories.xml',
        'https://www.lecho.be/rss/politique_belgique.xml',
        'https://www.lecho.be/rss/politique_economie.xml',
        'https://www.lecho.be/rss/politique_europe.xml',
        'https://www.lecho.be/rss/politique_internationale.xml',
        // 'http://blogs.lecho.be/fairtrade/rss.xml',
        'https://www.lecho.be/rss/les_cracks_en_action.xml',
        // 'http://blogs.lecho.be/monargent/rss.xml',
        // 'http://blogs.lecho.be/tzine/rss.xml',
        'https://www.lecho.be/rss/debats.xml',

        //LE VIF
        'http://www.levif.be/actualite/feed.rss',

        //LA RTBF
        'http://rss.rtbf.be/article/rss/highlight_rtbfinfo_info-accueil.xml',
        'http://rss.rtbf.be/media/rss/audio/lapremiere_recent.xml',

        //SUDINFO
        'http://www.sudinfo.be/rss/2023/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2023/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2089/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2144/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2092/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2093/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2146/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2147/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2094/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2900/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2921/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2095/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2096/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2145/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2090/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2091/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/1998/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2098/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2128/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2129/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2104/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2125/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2107/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2132/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2133/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2110/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2120/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2121/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2103/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2116/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2117/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2111/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2118/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2119/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2105/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2122/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2123/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2100/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2126/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2127/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2102/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2130/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2131/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2109/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2134/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2135/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2101/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2136/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2137/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2106/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2138/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2139/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2108/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2140/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2099/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2142/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2021/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2024/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2031/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2032/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2033/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2025/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2026/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2027/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2028/cible_principale_gratuit',
        'https://www.sudinfo.be/rss2/2030/cible_principale_gratuit',

        // FRANCE INFO
        'https://www.francetvinfo.fr/titres.rss',
        'https://www.francetvinfo.fr/france.rss',
        'https://www.francetvinfo.fr/politique.rss',
        'https://www.francetvinfo.fr/societe.rss',
        'https://www.francetvinfo.fr/faits-divers.rss',
        'https://www.francetvinfo.fr/justice.rss',
        'https://www.francetvinfo.fr/monde.rss',
        'https://www.francetvinfo.fr/afrique.rss',
        'https://www.francetvinfo.fr/ameriques.rss',
        'https://www.francetvinfo.fr/asie-pacifique.rss',
        'https://www.francetvinfo.fr/europe.rss',
        'https://www.francetvinfo.fr/proche-orient.rss',
        'https://www.francetvinfo.fr/environnement.rss',
        'https://www.francetvinfo.fr/eco.rss',
        'https://www.francetvinfo.fr/tendances.rss',
        'https://www.francetvinfo.fr/entreprises.rss',
        'https://www.francetvinfo.fr/marches.rss',
        'https://www.francetvinfo.fr/immobilier.rss',
        'https://www.francetvinfo.fr/sports.rss',
        'https://www.francetvinfo.fr/foot.rss',
        'https://www.francetvinfo.fr/rugby.rss',
        'https://www.francetvinfo.fr/f1.rss',
        'https://www.francetvinfo.fr/decouverte.rss',
        'https://www.francetvinfo.fr/sciences.rss',
        'https://www.francetvinfo.fr/sante.rss',
        'https://www.francetvinfo.fr/animaux.rss',
        'https://www.francetvinfo.fr/bizarre.rss',
        'https://www.francetvinfo.fr/culture.rss',
        'https://www.francetvinfo.fr/medias.rss',
        'https://www.francetvinfo.fr/cinema.rss',
        'https://www.francetvinfo.fr/musique.rss',
        'https://www.francetvinfo.fr/expos.rss',
        'https://www.francetvinfo.fr/internet.rss',

        // FRANCE 24
        'https://www.france24.com/fr/rss',
        'https://www.france24.com/fr/europe/rss',
        'https://www.france24.com/fr/france/rss',
        'https://www.france24.com/fr/afrique/rss',
        'https://www.france24.com/fr/moyen-orient/rss',
        'https://www.france24.com/fr/ameriques/rss',
        'https://www.france24.com/fr/asie-pacifique/rss',
        'https://www.france24.com/fr/economie/rss',
        'https://www.france24.com/fr/sports/rss',
        'https://www.france24.com/fr/culture/rss',
        'https://www.france24.com/fr/planete/rss',
        'https://www.france24.com/fr/decouvertes/rss',

        // LE PARISIEN
        'https://feeds.leparisien.fr/leparisien/rss/faits-divers',
        'https://feeds.leparisien.fr/leparisien/rss/politique',
        'https://feeds.leparisien.fr/leparisien/rss/economie',
        'https://feeds.leparisien.fr/leparisien/rss/international',
        'https://feeds.leparisien.fr/leparisien/rss/sports',
        'https://feeds.leparisien.fr/leparisien/rss/culture-loisirs',
        'https://feeds.leparisien.fr/leparisien/rss/immobilier',
        'https://feeds.leparisien.fr/leparisien/rss/environnement',
        'https://feeds.leparisien.fr/leparisien/rss/societe',
        'https://feeds.leparisien.fr/leparisien/rss',

        // BFM
        'https://www.bfmtv.com/rss/news-24-7/',
        'https://www.bfmtv.com/rss/sante/',
        'https://www.bfmtv.com/rss/auto/',
        'https://www.bfmtv.com/rss/culture/',
        'https://www.bfmtv.com/rss/international/',
        'https://www.bfmtv.com/rss/politique/',
        'https://www.bfmtv.com/rss/sciences/',
        'https://www.bfmtv.com/rss/environnement/',
        'https://www.bfmtv.com/rss/environnement/climat/',
        'https://www.bfmtv.com/rss/police-justice/',
        'https://www.bfmtv.com/rss/societe/',
        'https://www.bfmtv.com/rss/voyage/',
        'https://www.bfmtv.com/rss/animaux/',
        'https://www.bfmtv.com/rss/cuisine/',
        'https://www.bfmtv.com/rss/people/',
        'https://www.bfmtv.com/rss/people/mode/',
        'https://www.bfmtv.com/rss/people/cinema/',
        'https://www.bfmtv.com/rss/people/musique/',
        'https://www.bfmtv.com/rss/people/series/',
        'https://www.bfmtv.com/rss/tech/',
        'https://www.bfmtv.com/rss/tech/nouveautes-produits/',
        'https://www.bfmtv.com/rss/tech/culture-web/',
        'https://www.bfmtv.com/rss/tech/vie-numerique/',
        'https://www.bfmtv.com/rss/economie/',
        'https://www.bfmtv.com/rss/economie/votre-argent/',
        'https://www.bfmtv.com/rss/economie/votre-argent/immobilier/',
        'https://www.bfmtv.com/rss/economie/votre-argent/bourse/',
        'https://www.bfmtv.com/rss/economie/economie-social/france/',
        'https://www.bfmtv.com/rss/economie/economie-social/monde/',
        'https://www.bfmtv.com/rss/economie/entreprises/',
        'https://www.bfmtv.com/rss/economie/consommation/',
        'https://www.bfmtv.com/rss/economie/emploi/',
        'https://www.bfmtv.com/rss/economie/emploi/vie-de-bureau/',
        'https://www.bfmtv.com/rss/international/moyen-orient/',
        'https://www.bfmtv.com/rss/international/europe/',
        'https://www.bfmtv.com/rss/international/amerique-nord/',
        'https://www.bfmtv.com/rss/international/amerique-latine/',
        'https://www.bfmtv.com/rss/international/oceanie/',
        'https://www.bfmtv.com/rss/international/asie/',
        'https://www.bfmtv.com/rss/international/afrique/',
        'https://www.bfmtv.com/rss/temoins/meteo/',
        'https://www.bfmtv.com/rss/meteo/neige/',
        'https://www.bfmtv.com/rss/meteo/inondations/',
        'https://www.bfmtv.com/rss/meteo/canicule/',
        'https://www.bfmtv.com/rss/meteo/intemperies/',
        'https://www.bfmtv.com/rss/paris/',
        'https://www.bfmtv.com/rss/lyon/',
        'https://www.bfmtv.com/rss/grand-lille/',
        'https://www.bfmtv.com/rss/grand-littoral/',
        'https://www.bfmtv.com/rss/marseille/',
        'https://www.bfmtv.com/rss/toulouse/',
        'https://www.bfmtv.com/rss/ajaccio/',
        'https://www.bfmtv.com/rss/auxerre/',
        'https://www.bfmtv.com/rss/bastia/',
        'https://www.bfmtv.com/rss/besancon/',
        'https://www.bfmtv.com/rss/bordeaux/',
        'https://www.bfmtv.com/rss/brest/',
        'https://www.bfmtv.com/rss/caen/',
        'https://www.bfmtv.com/rss/clermont-ferrand/',
        'https://www.bfmtv.com/rss/dijon/',
        'https://www.bfmtv.com/rss/grenoble/',
        'https://www.bfmtv.com/rss/la-rochelle/',
        'https://www.bfmtv.com/rss/le-havre/',
        'https://www.bfmtv.com/rss/limoges/',
        'https://www.bfmtv.com/rss/metz/',
        'https://www.bfmtv.com/rss/montpellier/',
        'https://www.bfmtv.com/rss/nancy/',
        'https://www.bfmtv.com/rss/nantes/',
        'https://www.bfmtv.com/rss/nice/',
        'https://www.bfmtv.com/rss/orleans/',
        'https://www.bfmtv.com/rss/poitiers/',
        'https://www.bfmtv.com/rss/reims/',
        'https://www.bfmtv.com/rss/rennes/',
        'https://www.bfmtv.com/rss/saint-etienne/',
        'https://www.bfmtv.com/rss/strasbourg/',
        'https://www.bfmtv.com/rss/toulon/',
        'https://www.bfmtv.com/rss/tours/'
        ];
    }

    public static function mediasTag(){
        return [
            "sudinfo" => [".gr-article-content"],
            "rtbf"=> [".rtbf-paragraph"],
            "rtl"=> [".w-content-details-article-body"],
            "dhnet"=>[".article-text", ".articleText"],
            "lalibre"=> [".article-text", ".articleText"],
            "lecho"=> [".ac_paragraph"],
            "lesoir"=> [".gr-article-content"],
            "levif"=> [".article-body"]
        ];
    }

    function updateMediaName($em){
    $updateTable =
                [
                    "UPDATE media SET nom = 'rtl' where nom like '%rtl%'
                                or nom like 'feedproxy.google.com'
                    ",
                    "UPDATE media SET nom = 'dh' where nom like '%dh%'",
                    "UPDATE media SET nom = 'lecho' where nom like '%lecho%'
                                or nom like '%fair trade%' 
                                or nom like '%t-zine%'
                                or nom like '%tijd%'
                                or nom like '%cracks%'
                    ",
                    "UPDATE media SET nom = 'lesoir' where nom like '%lesoir%'",
                    "UPDATE media SET nom = 'lalibre' where nom like '%lalibre%'",
                    "UPDATE media SET nom = 'levif' where nom like '%vif%'",
                    "UPDATE media SET nom = 'rtbf' where nom like '%rtbf%'",
                    "UPDATE media SET nom = 'rtbf' where nom like '%la Première%'",
                    "UPDATE media SET nom = 'sudinfo' where nom like '%sudinfo%'"
                ];
        try {
            foreach ($updateTable as $key) {
                $stmt = $em->getConnection()->prepare($key);
                $stmt->execute();
            }
            return "Success";
        } catch (\Exception $e) {
            return "Error";
        }
    }
}